### PR TITLE
iop: rm ingress, update components

### PR DESCRIPTION
**Pull request by SamuAlfageme**
- And `"enable: true"` for all sub-components on the CI 
- Companion docs: https://github.com/sciencemesh/sciencemesh/commit/5e22436a488f4ed2e77c2db4511f0ffa474e23d6

### CODE REVIEW

**Review by dagl — APPROVED** [review]

**Review by dagl — COMMENTED** [review]
I get an erro:

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"

**Comment by SamuAlfageme** [comment]
@dagl have you run `helm dependency update <local-chart-path>/iop` before using the chart to upgrade your deployment? 

**Note that there is a slight change in the values, described in the [sciencemesh documentation](https://developer.sciencemesh.io/docs/iop/deployment/kubernetes/#configuring-an-iop-deployment)** (i.e. you have to nest the `ingress` settings under the `gateway` key). If you already did that, could you post the ingress manifest generated by helm when doing the upgrade with the `--dry-run --debug` flags?

**Comment by dagl** [comment]
yeah, I did run it, also I don't use iop ingress so that's weird. Here is the output:

```
cern@cern1:~/k8s/reva5$ helm upgrade --install -n default iop ~/git/samu/sciencemeshcharts/iop \
  --set wopiserver.enabled=true \
  --set gateway.persistentVolume.enabled=true \
  --set gateway.persistentVolume.existingClaim=iop-pvc \
  --set-file gateway.configFiles.revad\\.toml=standalone.toml \
  --set-file gateway.configFiles.gateway\\.toml=standalone.toml \
  --set-file gateway.configFiles.users\\.json=ext-users-ailleron.json  \
  --set wopiserver.config.iopsecret=* \
  --set gateway.env.REVA_APPPROVIDER_IOPSECRET=* \
  --set gateway.imagePullSecrets.name=regcred \
  -f home-sp.yaml -f reva-sp.yaml -f wopi.yaml -f wopibridge.yaml \
  --dry-run --debug
  
history.go:52: [debug] getting history for release iop
Release "iop" does not exist. Installing it now.
install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: /home/cern/git/samu/sciencemeshcharts/iop

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"
helm.go:84: [debug] unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:252
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:229
main.newUpgradeCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/upgrade.go:104
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
 ```

**Comment by SamuAlfageme** [comment]
@dagl give it another try, I've fixed an issue that went unnoticed when I introduced the support for the new ingress APIs. Thanks for reporting ❤️

**Comment by dagl** [comment]
Sure, got another error:

```
history.go:52: [debug] getting history for release iop
Release "iop" does not exist. Installing it now.
install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: /home/cern/git/samu/sciencemeshcharts/iop

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "service" in io.k8s.api.networking.v1beta1.IngressBackend
helm.go:84: [debug] error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "service" in io.k8s.api.networking.v1beta1.IngressBackend
helm.sh/helm/v3/pkg/kube.scrubValidationError
        /home/circleci/helm.sh/helm/pkg/kube/client.go:570
helm.sh/helm/v3/pkg/kube.(*Client).Build
        /home/circleci/helm.sh/helm/pkg/kube/client.go:159
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:250
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:229
main.newUpgradeCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/upgrade.go:104
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:252
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:229
main.newUpgradeCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/upgrade.go:104
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```

**Comment by SamuAlfageme** [comment]
@dagl I spotted the issue and extended this check to https://github.com/cs3org/charts/blob/5cbe76370a73ed6375a027de27e375cf1cad845c/revad/templates/ingress.yaml#L20 - it should be fixed now

**Comment by dagl** [comment]
Seems to work!

**Pull request merged**
