### PR TITLE
Add codimd to Meshapps umbrella chart

### LINKED ISSUE #74: Add CodiMD K8s chart to the IOP
Upstream chart:
https://hub.helm.sh/charts/codimd/codimd

### PR DESCRIPTION
**Pull request by SamuAlfageme**
This also fixes an issue with the default `collabora` image value as well as some wrong terms in the README. 

Closes https://github.com/sciencemesh/sciencemesh/issues/74

### CODE REVIEW

**Comment by Daniel-WWU-IT** [comment]
There are a few more environment variables we've set in our test deployment; not sure if they're really needed:
- CMD_SAVE_WEBHOOK: https://sciencemesh-test.uni-muenster.de/wbridge/save
- CMD_APPLIANCE_MODE: true
- CMD_URL_PATH: codimd

**Comment by SamuAlfageme** [comment]
@Daniel-WWU-IT thanks a lot for your review ❤️ 

The `CMD_APPLIANCE_MODE` set to `true` is already present on the values that are part of this PR: 

https://github.com/sciencemesh/charts/blob/1bf6f935549a4585f898ec6be8f32b879ea9674e/meshapps/values.yaml#L23

And indeed, the `URL_PATH` and `SAVE_WEBHOOK` are considered site-specific values and mentioned on [the companion doc PR](https://github.com/sciencemesh/sciencemesh/blob/e0658c4ca53af9f8109f641b6d8f4c3d49e785ba/docs/content/en/docs/Integrations/codimd.md#deploying-codimd-through-the-sciencemeshmeshapps-chart)

**Comment by glpatcern** [comment]
> And indeed, the `URL_PATH` and `SAVE_WEBHOOK` are considered site-specific values and mentioned on [the companion doc PR](https://github.com/sciencemesh/sciencemesh/blob/e0658c4ca53af9f8109f641b6d8f4c3d49e785ba/docs/content/en/docs/Integrations/codimd.md#deploying-codimd-through-the-sciencemeshmeshapps-chart)

[Reviewing some backlog] I agree with you Samuel, nevertheless any chance to "parameterize" such variables? In particular the `CMD_SAVE_WEBHOOK` must always look like `https://<ingress>/<wopibridge_path>/save`.

**Comment by SamuAlfageme** [comment]
@glpatcern I agree, making the config as lean as possible (as in no. of variables to be passed to deploy the chart) and avoiding duplicated variables/content is always a design goal I try to apply. For instance, that is how we generate the [WOPI Server/Bridge External URLs](https://github.com/cs3org/charts/blob/c132847a56728321697c341e587e4fce4b68b9fa/wopiserver/templates/_helpers.tpl#L66-L101) currently.

The issue to generate the `CMD_SAVE_WEBHOOK` content lies in how the two charts are decoupled: there is no way to access the IOP-specific variables (e.g. the WOPI Bridge ingress hostname and path) from a different chart (MESHApps, in this case).

This could be done if we ever consider creating a meta-umbrella chart that agglutinates these two by using [Helm's `global` chart values](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#global-chart-values).

**Pull request merged**
